/* 
 * File:   main.cpp
 * Author: Sarah Alfeerawi
 * Created on July 5, 2015, 9:50 PM
 * Purpose: To Calculate the Income from Ticket Sales
 */

//System Libraries
#include <iostream>
#include <iomanip>
using namespace std;

//User Libraries

//Global Constants

//Function Prototype

//Execution begins here!
int main(int argc, char** argv) {
    //Declare and Initialize Variables
    float costA=15.00f;   //Cost of class A tickets in dollars
    float costB=12.00f;   //Cost of class B tickets in dollars
    float costC=9.00f;    //Cost of class C tickets in dollars
    unsigned int ticketA; //Number of class A tickets sold
    unsigned int ticketB; //Number of class B tickets sold 
    unsigned int ticketC; //Number of class C tickets sold
    float income;         //Income generated from total ticket sales
    
    //Input Values
    cout<<"Input number of class A tickets sold: "<<endl; 
    cin>>ticketA;
    cout<<"Input number of class B tickets sold: "<<endl;
    cin>>ticketB;
    cout<<"Input number of class C tickets sold: "<<endl;
    cin>>ticketC;
    
    //Calculate Income Generate
    income=(costA*ticketA+costB*ticketB+costC*ticketC); //Equation for income
    
    //Output Results
    cout<<"Income generated by ticket sales: $"
            <<showpoint<<fixed<<setprecision(2)<<income<<endl;
            
    //Exit Stage Right!

    return 0;
}

